#define SECRET_SSID "hyuksoo_hotspot"
#define SECRET_PASS "gurtnrla*808"
#define SECRET_BROKER "a2r9lko9bua02e-ats.iot.ap-northeast-2.amazonaws.com"

const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICkDCCAXigAwIBAgIUR6TI+SKj/MnlxB1na8mXo6ZZdF8wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMTEyNjA3NDAw
OVoXDTQ5MTIzMTIzNTk1OVowIDEeMBwGA1UEAxMVUHJvamVjdF9NeU1LUldpRmkx
MDEwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMGFkmHintFumUVOp+Hh77qPL
8hxCA2kXhumHwl+OiXcSllW+YelsGyEEbtoxiZ1nA2/A/udAwXaRDdv0/VqGtqNg
MF4wHwYDVR0jBBgwFoAUAuaxXnB27QqEhaw9n/qscfze/lcwHQYDVR0OBBYEFDau
RkcDkzSuC0jcJU3ekqS6cZoyMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeA
MA0GCSqGSIb3DQEBCwUAA4IBAQBEQU/7JrTIhek8Wjf8hikwtusamm7XNK8Mcih+
eFG/D1yvTaYfPucqYxSYret0PTQtPcclxvaeYVpt7bydnQr8rucU8lFP3KDpZlP5
xPj7xqzlzFOW9W07xOm4CJZgZPPLx1p8TMSRzcCShS9+ZuMHPMAkO4lijvQ4+XZK
xwVqWDfg1ehx3LllqBPKUEqRBA5DolkTbDLnSZWSsRSymjuFYOLN5Vo6ZaB9gAV0
GPsxmIMyu3AKgo6m4gGSHspQ+vdhE3jFVFgP35NF61HjBJcAeHgEV7P3HRjjlgP2
0D/nTBbGTbwXDuEvuvy5tSG5Ory1zgDxcPavu25l2bC6hsAK
-----END CERTIFICATE-----
)";
